db_file            "~/.config/mpd/database"

log_file "~/.config/mpd/mpd.log"

music_directory    "/home/{$USER}/Music"


follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"

audio_output {
    type    "alsa"
    name    "My ALSA Device"
    device "default"          
    mixer_control "PCM"        
    mixer_type      "software"
}

audio_output {
   type   "fifo"
   name   "my_fifo"
   path   "/tmp/mpd.fifo"
   format "44100:16:2"
}

