[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"


[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.tinymist]
command = "tinymist"


[[language]]
name = "typst"
language-servers = ["tinymist"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]


[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "emmet-lsp" ]


[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "emmet-lsp" ]


[language-server.ron-lsp]
command = "ron-lsp"

[[language]]
name = "ron"
language-servers = ["ron-lsp"]
