[main]
font=JetBrainsMono Nerd Font:size=12
terminal=ghostty
prompt="❯ "
layer=overlay

# Layout
width=40
horizontal-pad=20
vertical-pad=10
inner-pad=5

[colors]
background=282a36ff
text=f8f8f2ff
match=8be9fdff
selection=44475aff
selection-text=f8f8f2ff
selection-match=8be9fdff
border=bd93f9ff

[border]
width=2
radius=10
